import { ColumnType, Generated, Insertable, Selectable, Updateable } from 'kysely'

export interface Database {
  file: FileTable
}

export interface FileTable {
  // Columns that are generated by the database should be marked
  // using the `Generated` type. This way they are automatically
  // made optional in inserts and updates.
  id: Generated<number>
  name: string
  size: number
  created_at: ColumnType<Date, string | undefined, never>
}

// You should not use the table schema interfaces directly. Instead, you should
// use the `Selectable`, `Insertable` and `Updateable` wrappers. These wrappers
// make sure that the correct types are used in each operation.
export type Person = Selectable<FileTable>
export type NewPerson = Insertable<FileTable>
export type PersonUpdate = Updateable<FileTable>

